### ISSUE TITLE
Failed to repair

### ISSUE THREAD

**Issue by seegersnl** [jangxx/node-magichome#12]
After i reboot homey or my router, al my devices are unreachable. The magic home app can find the device, maybe because a new ip adres or something. Can you lock the device on a mac adress?

**Comment by jangxx** [comment]
No, but you can use the unique 12 character id (which might very well be MAC addresses, idk) each controller has. Simply call `Discovery.scan()` to find all devices in your network. You'll get IP addresses and device ids for each of them, so you can simply store the ids and then match the addresses to them. Be warned however, that the controllers tend to not reply to the discovery on the first or even the second try. This is an issue internal to the controllers however, so you have to work around it yourself.

**Comment by jghaanstra** [comment]
This should have been posted in the [Magic Home Homey app repo](https://github.com/jghaanstra/magic.home.wifi) which uses this library. I'll add some sort of support for discovery for devices with changed IP addresses due to DHCP. This can be closed.

**Comment by jangxx** [comment]
Okay, thanks for the heads up.
