### ISSUE TITLE
Buffer difference for `setColor` command?

### ISSUE THREAD

**Issue by chasdevs** [jangxx/node-magichome#16]
I'm attempting to use this library to control a set of light bulbs on my LAN. For my bulbs (the [BERENNIS Smart Light Bulb](https://www.amazon.com/gp/product/B07GGWNQT7/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1)) most of the commands work, but `setColor` and all other color-related functions do not. 

Using Wireshark I saw that the python library, for the same command, was sending `0x31, red, green, blue, ww, 0xf0, 0x0f`. This library sends `0x31, red, green, blue, ww, 0, 0x0f`.

I'm not sure why there is a difference; it could be the type of bulb or something. Just wanted to record what I found in case it helps anyone else.

**Comment by chasdevs** [comment]
Looking through your other issues, it appears this may be an expected edge case. Feel free to close this if not useful.

**Comment by jangxx** [comment]
Yes, you are right, this is an edge case I have not yet dealt with, since I don't have any devices which exhibit this behavior. If you want, I could add the type field of the query response to the returned object of `queryState` and provide an additional optional write mask parameter for the color related commands. The type field could then be used to determine if a write mask is actually needed.

**Comment by chasdevs** [comment]
Yeah that could help if it's not too much trouble. I can always bail to python but much prefer Typescript these days.

**Comment by jangxx** [comment]
Okay, I will implement this feature in the coming days. Stay posted for an update to 2.1.0.

**Comment by jangxx** [comment]
Version 2.1.0 is done and published to npm. As I said, I don't have any of these bulbs, so I could not test this implementation beyond checking that the existing functionality did not break. I would be happy if you could test the new features with your bulbs. I also wrote more JsDoc comments, which should improve you experience when using this library from TypeScript.

**Comment by chasdevs** [comment]
@jangxx Works great! The color sets no problem; the only issue right now is that the Promise does not return for the color commands (something I encountered when I messed with the source code, too). It's easy enough to not wait for the response, but having a valid response would be nice. I may have some spare time today and can take a crack at a PR.

**Comment by jangxx** [comment]
You just have to set the `wait_for_reply` option to `false` in the constructor if your controllers don't acknowledge the commands.
