### ISSUE TITLE
New type

### ISSUE THREAD

**Issue by garbagefactory** [jangxx/node-magichome#32]
![image](https://user-images.githubusercontent.com/28468594/103161002-f6c3bc00-47a9-11eb-946b-3cd69ee6cb1e.png)

- turning it on/off works
- setting pattern works
- setting color does not work

Tried setting with ackMasks but it doesn't fix it. Is this type supported?

**Comment by jangxx** [comment]
Type `0x25` is a bulb and not a controller, so you need to set the `apply_masks` option to `true` (as stated in the README) and use `setColor` and `setWarmWhite` instead of `setColorAndWarmWhite`. You can also call `queryState` once before sending any other commands, which will set this option automatically:

```javascript
const control = new Control(ADDRESS);
await control.queryState(); // will silently set apply_masks to true
await control.setColor(255, 255, 255); // will now send the correct command
```

**Comment by garbagefactory** [comment]
I have tried this and the command is still timing out. 

```
const { Control } = require('magic-home');

async function thing(){
	const ip = "[MY IP]"

	const control = new Control(ip);
	await control.queryState(); 
	await control.setColor(0, 255, 255); 


}
thing();

```
![image](https://user-images.githubusercontent.com/28468594/103181616-0823cb80-4871-11eb-80d8-07c5bb03722a.png)

I am using an RGB LED strip.

**Comment by jangxx** [comment]
Well, but does the color change work or not? The timeout probably happens because you need to set the `ack` parameter correctly, but the color change should still happen without it.

**Comment by garbagefactory** [comment]
The color change does not occur unfortunately.

**Comment by garbagefactory** [comment]
I'm going to try setting up an ack and trying it then, I'll get back to you.

**Comment by garbagefactory** [comment]
Nope. Modified the Control portion to include an ack and I'm getting nothing.

`const control = new Control(ip, {wait_for_reply: true, apply_masks: true, ack: {power: true, color: true, pattern: true, custom_pattern: true}});
`

**Comment by jangxx** [comment]
Do your bulbs have cold white colors as well? In that case you need to enable `cold_white_support` as well. Also, please don't use the `wait_for_reply` parameter, especially not together with the `ack` parameter.

Also, when you say you are "getting nothing", are you still only talking about setting the colors, or do the other commands not work as well?

**Comment by jangxx** [comment]
Closed due to inactivity
