### ISSUE TITLE
Multi Device Support

### ISSUE THREAD

**Issue by SkyBird1980** [jangxx/node-magichome#34]
Hi, can you please add a multi device config node so you can have more than one device in the network? :)

**Comment by jangxx** [comment]
I don't think I understand your question. If you want to control multiple devices, you can easily create multiple `Control` instances.

For example:
```javascript
const { Control } = require("magic-home");

const devices = [ "192.168.1.10", "192.168.1.11", "192.168.1.12" ].map(ip => new Control(ip));

// query the state of all devices to set some config params automatically
await Promise.all(devices.map(device => device.queryState()));

// turn on all three devices
await Promise.all(devices.map(device => device.turnOn()));

// set all devices to red
await Promise.all(devices.map(device => device.setColor(255, 0, 0)));
```

**Comment by SkyBird1980** [comment]
uff i meant the node-red node, sorry

**Comment by jangxx** [comment]
Well in that case you need to raise an issue with the developers of that specific node-red plugin. This is just the underlying library and has nothing to do with node-red.

**Comment by SkyBird1980** [comment]
Ok thank you :) this github was linked so i thought you're the one. Sorry.
