### ISSUE TITLE
Feature request: Connection state

### ISSUE THREAD

**Issue by tedstriker** [jangxx/node-magichome#9]
Is it possible to expose the connection state to the ESP and fire events ob change of it?

**Comment by jangxx** [comment]
It would be possible to emit "connect" and "disconnect" event for example, but I'm not sure I understand why you would want to have that. The library does not keep a permanent connection to the controllers - it only connects to send a single command and then kills the connection, except when new commands are sent before. In that case the additional commands are queued and sent one after another until then queue is empty.

If the library emitted events you would have stuff like

    _sendCommand() -> "connect" emitted -> "disconnect" emitted

all in the span of less than a second if the connection can be established immediately. If it can't, the command is still queued and will be sent out when `_sendCommand()` is called at a later time.

**Comment by jangxx** [comment]
If you want to detect a connection error like ECONNREFUSED you can look at the error parameter of the callback. Socket errors will be passed through there. If you actually want to detect the availability tough, your best bet is probably either pings, periodic discovery scans, or periodic `queryState()` calls. Personally I would go with one of the first two, depending on whether you know the IP to be static or changing.

**Comment by tedstriker** [comment]
That sounds good! I think I'll go for the discovery option.
